# Generated by Django 4.0.3 on 2022-03-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('eco', models.BooleanField()),
                ('adress', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=500)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.material')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.company')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.material')),
            ],
        ),
    ]
