# Generated by Django 4.0.3 on 2022-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='8 800 555 35 35', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='web_link',
            field=models.URLField(default='example.com'),
        ),
    ]
