# Generated by Django 4.0.3 on 2022-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_company_phone_company_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='warning',
            field=models.CharField(default='', max_length=500),
        ),
    ]
