# Generated by Django 4.0.3 on 2022-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_company_phone_company_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='materials',
            field=models.ManyToManyField(to='myapi.material'),
        ),
    ]
