# Generated by Django 4.0.3 on 2022-03-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_company_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('consist', models.CharField(max_length=500)),
                ('notify', models.CharField(max_length=100)),
                ('eco', models.BooleanField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.material')),
            ],
        ),
    ]
