# Generated by Django 4.0.3 on 2022-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_ware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hey', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Ware',
        ),
    ]
