# Generated by Django 4.0.3 on 2022-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_hey_delete_ware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hey',
            name='hey',
            field=models.CharField(default='8 800 555 35 35', max_length=30),
        ),
    ]
