# Generated by Django 4.0.3 on 2022-03-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_hey_hey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=13)),
                ('name_ware', models.CharField(max_length=100)),
                ('consist', models.CharField(max_length=500)),
                ('eco', models.BooleanField()),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.marks')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.material')),
            ],
        ),
        migrations.CreateModel(
            name='WareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Hey',
        ),
        migrations.AddField(
            model_name='ware',
            name='ware_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.waretype'),
        ),
    ]
