# Generated by Django 4.0.3 on 2022-03-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_ware_waretype_delete_hey_ware_ware_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='mark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.marks'),
        ),
    ]
