# Generated by Django 4.0.3 on 2022-03-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_ware_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.marks'),
        ),
    ]
