# Generated by Django 4.0.3 on 2022-03-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alter_ware_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='mark',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapi.marks'),
            preserve_default=False,
        ),
    ]
